# Generated by Django 4.2.6 on 2023-10-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='nrcs',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='ramos',
        ),
    ]
