# Generated by Django 4.2.6 on 2023-10-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_remove_profesor_nrcs_remove_profesor_ramos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='carreras',
        ),
    ]
