# Generated by Django 4.2.6 on 2023-11-05 22:16

import applications.profesores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0003_remove_profesor_carreras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='rut',
            field=models.CharField(blank=True, max_length=100, unique=True, validators=[applications.profesores.models.Profesor.validar_rut]),
        ),
    ]
