# Generated by Django 4.2.6 on 2023-11-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carrera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
