# Generated by Django 4.2.6 on 2023-11-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asking_rol',
            field=models.CharField(blank=True, choices=[('1', 'Admin'), ('2', 'Secretario'), ('3', 'Estudiante')], max_length=50, null=True),
        ),
    ]
