# Generated by Django 4.2.6 on 2023-10-12 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
        ('profesores', '0001_initial'),
        ('carreras', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrc',
            name='docentes',
            field=models.ManyToManyField(blank=True, to='profesores.profesor'),
        ),
        migrations.AddField(
            model_name='nrc',
            name='horarios',
            field=models.ManyToManyField(blank=True, to='horarios.horariodenrcs'),
        ),
        migrations.AddField(
            model_name='nrc',
            name='ramo_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.ramo'),
        ),
    ]
