# Generated by Django 4.2.6 on 2023-10-30 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_remove_profesor_nrcs_remove_profesor_ramos'),
        ('horarios', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nrc',
            name='docentes',
        ),
        migrations.AddField(
            model_name='nrc',
            name='docentes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='profesores.profesor'),
        ),
    ]
