# Generated by Django 4.2.6 on 2023-10-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('semestres_totales', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('creditos', models.PositiveIntegerField(blank=True)),
                ('codigo', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('carreras', models.ManyToManyField(blank=True, to='carreras.carrera')),
                ('correquisito', models.ManyToManyField(blank=True, to='carreras.ramo')),
            ],
            options={
                'verbose_name': 'Ramo',
                'verbose_name_plural': 'Ramos',
            },
        ),
    ]
