# Generated by Django 4.2.6 on 2023-10-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_remove_profesor_nrcs_remove_profesor_ramos'),
        ('carreras', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='ramos', to='profesores.profesor'),
        ),
    ]
