# Generated by Django 4.2.6 on 2023-11-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_alter_ramo_profesores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='ramos',
        ),
        migrations.AlterField(
            model_name='ramo',
            name='carreras',
            field=models.ManyToManyField(blank=True, related_name='ramos', to='carreras.carrera'),
        ),
    ]
